// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: password_reset_tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const storePasswordToken = `-- name: StorePasswordToken :one
INSERT INTO password_reset_tokens (token, user_id, created_at, expires_at)
VALUES (
    $1,
    $2,
    NOW(),
    $3
)
RETURNING token, user_id, created_at, expires_at, used_at
`

type StorePasswordTokenParams struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) StorePasswordToken(ctx context.Context, arg StorePasswordTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, storePasswordToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
